2025-08-08 16:50:53.366 | INFO     | __main__:_load_config:60 - 成功加载配置文件: config.toml
2025-08-08 16:50:53.366 | INFO     | __main__:__init__:45 - DifyRetrieval客户端初始化成功
2025-08-08 16:50:53.367 | INFO     | __main__:<module>:301 - 开始测试所有配置...
2025-08-08 16:50:53.367 | INFO     | __main__:retrieve_configs:159 - 开始遍历配置数组测试检索效果
2025-08-08 16:50:53.367 | INFO     | __main__:retrieve_configs:167 - 找到 1 个配置项
2025-08-08 16:50:53.367 | INFO     | __main__:retrieve_configs:170 - 正在测试配置: hybrid_search
2025-08-08 16:50:53.371 | INFO     | __main__:retrieve:105 - 开始检索知识库: fa675d48-8071-484a-a5bd-6ee7e84e0671
2025-08-08 16:51:14.407 | ERROR    | __main__:retrieve_configs:202 - 配置 hybrid_search 测试失败: HTTPConnectionPool(host='10.10.0.22', port=80): Max retries exceeded with url: /v1/datasets/fa675d48-8071-484a-a5bd-6ee7e84e0671/retrieve (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024DCBBBD6D0>, 'Connection to 10.10.0.22 timed out. (connect timeout=None)'))
2025-08-08 16:51:14.407 | INFO     | __main__:retrieve_configs:204 - 配置测试完成
2025-08-08 16:51:14.407 | INFO     | __main__:<module>:305 - 
测试结果摘要:
2025-08-08 16:51:14.407 | ERROR    | __main__:<module>:313 - - hybrid_search: 失败 (HTTPConnectionPool(host='10.10.0.22', port=80): Max retries exceeded with url: /v1/datasets/fa675d48-8071-484a-a5bd-6ee7e84e0671/retrieve (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024DCBBBD6D0>, 'Connection to 10.10.0.22 timed out. (connect timeout=None)')))
